# Generated by Django 5.1.4 on 2024-12-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0002_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
